### ISSUE TITLE
[Question] Usage with cssnano

### ISSUE THREAD

**Issue by bigopon** [rtsao/babel-plugin-csjs-postcss#2]
Hi, when i use csjs together with cssnano,

I get an error: **Use process(css).then(cb) to work with async plugins**

My config with webpack:

``` javascript
{ test: /\.js$/, exclude: /node_modules/, loader: 'babel-loader',
    query: {
        presets: ['es2015', 'stage-0'],
        plugins: [
            /*"transform-es2015-modules-simple-amd",*/
            "transform-es2015-modules-simple-commonjs",
            [ 'csjs-postcss', { plugins: ['postcss-cssnext', 'cssnano'] } ]
        ]
    }
}
```

How can I do to make it work with cssnano ?

**Comment by rtsao** [comment]
Thanks for pointing this out. I'm guessing cssnano doesn't support the synchronous PostCSS API.

This is the relevant code in this module where PostCSS is run: https://github.com/rtsao/babel-plugin-csjs-postcss/blob/master/src/index.js#L24-L25 Unfortunately, it appears Babel does not support asynchronous transformations [1][2] so until it does, I don't think this plugin will be able to support plugins that require the async PostCSS API. :disappointed: 

[1] https://github.com/babel/babel.github.io/issues/762
[2] https://phabricator.babeljs.io/T7154

I'm not sure why cssnano doesn't work synchronously.
https://github.com/ben-eb/cssnano/issues/68

**Comment by scott113341** [comment]
It works!  @drcmda figured it out: see rtsao/csjs#60

**Comment by rtsao** [comment]
https://github.com/hail2u/node-csswring works.
