### ISSUE TITLE
Autoprefixer not working

### ISSUE THREAD

**Issue by gersomvg** [rtsao/babel-plugin-csjs-postcss#3]
Any ideas why this is not working in my package.json (using browserify)?

`"start": "budo src/main.js:build/script/bundle.js --live --open -- -t [ babelify --presets [ es2015 react ] --plugins [ csjs-postcss --plugins [ autoprefixer ] ] ] -t [ csjs-injectify ] & npm run test:watch"`

Everything works fine, including style injection, but the prefixer does not do it's job. A sample csjs file looks like this:

```
import csjs from 'csjs'
import colors from './colors'

const styles = csjs`
  .normal {
    font-family: 'Roboto', sans-serif;
    line-height: 1.2;
    font-weight: 400;
    font-size: 15px;
    color: ${colors.text};
    filter: grayscale(100%);  // This should be prefixed
  }
`

export default styles
```

I cannot see from the docs if this is even supposed to be compatible with csjs-injectify... If that is not the case: is there already some combination of plugins that enables me to use csjs **with** Browserify **and** autoprefixer?

**Comment by rtsao** [comment]
Try using a `.babelrc` rather than specifying babel options via command line arguments. I suspect the problem is the `plugins` option containing `autoprefixer` is not being correctly passed to `csjs-postcss`.

I think budo/browserify/babelify might not support passing options to babel plugins in that fashion, but a `.babelrc` should work just fine.

**Comment by gersomvg** [comment]
You are right. I just nailed it down to the plugins option not being passed correctly. Thanks for the quick response!

I really hope that your invention gains more traction, because csjs is in my opinion the best, simplest and most balanced implementation of css in js. And I did quite some research ;)
